### ISSUE TITLE
White screen

### ISSUE THREAD

**Issue by X52p** [jaelpark/chamferwm#11]
I installed chamferWM via AUR.
When using the following command in xinit.rc:

`exec chamfer --config=/usr/share/chamfer/config/config.py --shader-path=/usr/share/chamfer/shaders/`

I only get a blank white screen.

I also tried:
`exec stdbuf -oL chamfer --shader-path=/usr/share/chamfer/shaders/ > /tmp/log`
but the log does not contain any errors

**Comment by jaelpark** [comment]
The background will be blank white by default if no wallpaper or other color is set. Are you able to get any response to you input? If you configure your default [terminal emulator](https://github.com/jaelpark/chamferwm/blob/43649ad5ade959d6846ff6f2f7341703fb96415d/config/config.py#L537) or [browser](https://github.com/jaelpark/chamferwm/blob/43649ad5ade959d6846ff6f2f7341703fb96415d/config/config.py#L540) for instance, you should be able to see the applications get launched when you press mod+Enter or Super+1, respectively.

**Comment by X52p** [comment]
I can't open the terminal, or any other Programm. (edit: the Mouse Cursor is visible)

**Comment by jaelpark** [comment]
Can you test the window manager without compositor? If you use
``exec chamfer --config=/usr/share/chamfer/config/config.py -n``
instead, is it possible to launch applications?

One should also try if the compositor has the basic capacity to work as expected. In your regular WM/DE, you could run
``chamfer -d --config=/usr/share/chamfer/config/config.py --shader-path=/usr/share/chamfer/shaders/``
Here ``-d`` creates a test environment for the compositor in a regular window while running in another WM/DE. Once running, does Shift+Space have any effect? It should create a frame inside this window.

**Comment by dedguy21** [comment]
The above instructions worked inside awesome.wm thank you.

**Comment by dedguy21** [comment]
We should probably close this as the above solution worked
