### ISSUE TITLE
why?

### ISSUE THREAD

**Issue by ghost** [jaelpark/chamferwm#12]
![image](https://user-images.githubusercontent.com/40970965/70631530-0bb7c680-1c0c-11ea-9451-858535e095ae.png)

**Comment by jaelpark** [comment]
Yea, it's off... 😅

One can switch to basic rectangular borders by changing a [definition](https://github.com/jaelpark/chamferwm/blob/ed8b7079a2b13d0c532423263b757b29829ded93/shaders/frame.hlsl#L55) in the main fragment shader.

Anyway, you're looking at a rather old screenshot, I should post a new one soon where these issues have already been fixed.
