### ISSUE TITLE
Multi-monitor Set-up?

### ISSUE THREAD

**Issue by dedguy21** [jaelpark/chamferwm#18]
Does chamferWM support multi monitor? And if so, what variable would I use for my monitor config?

Thank you.

**Comment by jaelpark** [comment]
As of yet Chamferwm unfortunately does not support multi-monitor setups. However, support for workspaces across multiple monitors is something I've been planning to implement next as I would also need this myself quite a lot. I'm looking into how to get it reasonably done, but there will be some work to it. I'm hoping to make some progress in near future..

**Comment by dedguy21** [comment]
It's been three years. Sorry for not closing it sooner.
