### ISSUE TITLE
How is the ICCCM and EWMH support?

### ISSUE THREAD

**Issue by wis** [jaelpark/chamferwm#22]
I'm asking because I'm considering using chamferwm and I use [sxhkd](https://github.com/baskerville/sxhkd) as a hotkey daemon and wmctrl to change workspaces and window focus, position and size.

**Comment by jaelpark** [comment]
The support is partial at the moment, and I think most of the support covers retrieval of attributes from the wm. Some features, such as changing the focus, is supported however. Adding the missing essential protocols is not too complicated, I might have some time this week to revisit it.

**Comment by jaelpark** [comment]
I implemented the EWMH workspace protocol, which after testing with wmctrl appears to work fine. Other actions that are already working include focusing, closing and fullscreening windows. Move/resize is not implemented yet, but I will most likely look into it soon as well to complete the basic support.

**Comment by jaelpark** [comment]
I think the requested functionality was added and should be working, so I'm closing this one for now. Move/resize works for floating windows. Moving across workspaces works as well. Let me know if you ever try it, but something essential is still missing or not fully functional.
