### ISSUE TITLE
Steam input doesn't work

### ISSUE THREAD

**Issue by ktheticdev** [jaelpark/chamferwm#23]
When I try to launch Steam, keyboard input works, but it won't recognize mouse clicks.

**Comment by jaelpark** [comment]
Thanks for the report. I've had this same issue actually, but not yet sure what causes it. Needs further investigation

**Comment by jaelpark** [comment]
I made a change that seems to resolve the issue. In my testing mouse interaction and menus all work now. There still seems to be some strange behavior with popup menus being animated, but it doesn't seem to affect the usability. It doesn't happen when the compositor is disabled (alt+0), which I'd recommend anyway for gaming.
