### ISSUE TITLE
Compilation on debian 10

### ISSUE THREAD

**Issue by fabienjean** [jaelpark/chamferwm#24]
Hi
I try to compile the project on debian 10 and i have lot of error. do you have any idea ?

        ^~~~~
../src/CompositorResource.cpp:776:1: error: could not convert ‘{{"POSITION", VK_FORMAT_R32G32_SFLOAT, 8}, {"POSITION", VK_FORMAT_R32G32_UINT, 8}, {"TEXCOORD", VK_FORMAT_R32G32_SFLOAT, 8}, {"TEXCOORD", VK_FORMAT_R32G32_UINT, 8}}’ from ‘<brace-enclosed initializer list>’ to ‘const std::vector<std::tuple<const char*, VkFormat, unsigned int> >’
 };
 ^
../src/CompositorResource.cpp:789:1: error: could not convert ‘{{"xy0", 8}, {"xy1", 8}, {"transform", 16}, {"screen", 8}, {"margin", 8}, {"titlePad", 8}, {"titleSpan", 8}, {"stackIndex", 4}, {"flags", 4}, {"time", 4}}’ from ‘<brace-enclosed initializer list>’ to ‘const std::vector<std::tuple<const char*, unsigned int> >’
 };
 ^
../src/CompositorResource.cpp: In constructor ‘Compositor::Pipeline::Pipeline(Compositor::ShaderModule*, Compositor::ShaderModule*, Compositor::ShaderModule*, const std::vector<std::pair<Compositor::ShaderModule::INPUT, unsigned int> >*, const VkPipelineInputAssemblyStateCreateInfo*, const VkPipelineRasterizationStateCreateInfo*, const VkPipelineDepthStencilStateCreateInfo*, const VkPipelineColorBlendStateCreateInfo*, const VkPipelineDynamicStateCreateInfo*, const Compositor::CompositorInterface*)’:
../src/CompositorResource.cpp:801:186: error: no matching function for call to ‘get<0>(const value_type&)’
     DebugPrintf(stdout,"warning: semantic %s in %s at location %u not supported by the input buffer.\n",std::get<0>(ShaderModule::semanticMap[_pvertexShader->inputs[i].semanticMapIndex]),_pvertexShader->pname,_pvertexShader->inputs[i].location);
                                                                                                                                                                                          ^
In file included from /usr/include/c++/8/bits/stl_uninitialized.h:60,
                 from /usr/include/c++/8/vector:63,
                 from ../src/main.h:9,
                 from ../src/CompositorResource.cpp:1:
/usr/include/c++/8/utility:216:5: note: candidate: ‘template<long unsigned int _Int, class _Tp1, class _Tp2> constexpr typename std::tuple_element<_Int, std::pair<_Tp1, _Tp2> >::type& std::get(std::pair<_Tp1, _Tp2>&)’
     get(std::pair<_Tp1, _Tp2>& __in) noexcept
     ^~~
/usr/include/c++/8/utility:216:5: note:   template argument deduction/substitution failed:
../src/CompositorResource.cpp:801:186: note:   types ‘std::pair<_Tp1, _Tp2>’ and ‘const value_type’ {aka ‘const std::tuple<const char*, VkFormat, unsigned int>’} have incompatible cv-qualifiers
     DebugPrintf(stdout,"warning: semantic %s in %s at location %u not supported by the input buffer.\n",std::get<0>(ShaderModule::semanticMap[_pvertexShader->inputs[i].semanticMapIndex]),_pvertexShader->pname,_pvertexShader->inputs[i].location);
                                                                                                                                                                                          ^
In file included from /usr/include/c++/8/bits/stl_uninitialized.h:60,
                 from /usr/include/c++/8/vector:63,
                 from ../src/main.h:9,
                 from ../src/CompositorResource.cpp:1:
/usr/include/c++/8/utility:221:5: note: candidate: ‘template<long unsigned int _Int, class _Tp1, class _Tp2> constexpr typename std::tuple_element<_Int, std::pair<_Tp1, _Tp2> >::type&& std::get(std::pair<_Tp1, _Tp2>&&)’
     get(std::pair<_Tp1, _Tp2>&& __in) noexcept
     ^~~
Thanks

**Comment by jaelpark** [comment]
Hi, thanks for the report. The latest commit should fix the build. Feel free to reopen if there are more build issues.
