### ISSUE TITLE
Entry echo one character behind

### ISSUE THREAD

**Issue by juanitotc** [jaelpark/chamferwm#5]
At some point after starting chamferwm, the character echoed in the terminal starts to lag one character behind what has been entered.

For example, if I enter "ab", only "a" is echoed until I enter "c" at which point I can see "ab". I then have to enter "space" before I can see "abc".

**Comment by jaelpark** [comment]
Is there a chance that DPMS turned off the screen at some point before you started noticing the lagging? I have this annoying problem here that if the screen is turned off and on, and something gets rendered in between, it might result in the swap chain getting messed up somehow. This will result in the kind of symptoms you described.

**Comment by juanitotc** [comment]
No, it's nothing to do with dpms - it looks like it happens after opening two or more windows and switching back and forth between them?

**Comment by jaelpark** [comment]
Does it happen also if you pass  `--no-scissoring` as a command line flag?

**Comment by juanitotc** [comment]
I've been unable to recreate the problem - I'll reopen this if it happens again
