### ISSUE TITLE
Keystroke to start browser does not work

### ISSUE THREAD

**Issue by juanitotc** [jaelpark/chamferwm#6]
Assuming the keystroke combo to start a browser is "alt 1", it does not work for me.

The other keystroke combo's I've tried do work - allowing for "alt shift e" not making it to the tty.

**Comment by jaelpark** [comment]
Try Super+1😉. The modifier mask for this is set to mod4 by default, which is supposed to translate to Windows key. I really need to get that documentation up at some point...

> allowing for "alt shift e" not making it to the tty.

Still not sure yet why this happens. I don't have any system where this gets reproduced, need to see about this somehow.

**Comment by juanitotc** [comment]
Ah - yes "window 1" does start the browser - sorry for the noise.

On this system, exit to the console prompt is done using [ -n "$XPID" ] && sudo kill "$XPID"
